[project]
name = "MiraiChan_workspace"
version = "0.1.0"
description = "workspace for MiraiChan bot and plugins"
authors = [
    { name = "NingmengLemon", email = "60469383+NingmengLemon@users.noreply.github.com" },
]
dependencies = [
    "miraichan",
    # protocol adapters
    "melobot_telegram_protocol",
    # shared libs
    "lemony_utils",
    "lemony_settings",
    "lemony_checkers",
    "lemony_llm_provider",
    "lemony_storage_helper[all]",
    "lemony_images",
    "lemony_network",
    "lemony_media",
    "lemony_onebot_utils",
    # plugins
    "mbplugin_checker_manager",
    "mbplugin_deeeer",
    "mbplugin_moelottery",
    "mbplugin_recorder",
    # workspace members above
    "melobot[onebot]>=3.5.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "AGPL3" }

[tool.uv.workspace]
members = [
    "packages/miraichan",
    "packages/shared/*",
    "packages/plugins/mbplugin_checker_manager",
    "packages/plugins/mbplugin_deeeer",
    "packages/plugins/mbplugin_moelottery",
    "packages/plugins/mbplugin_recorder",
    # "packages/plugins/*",
]

[tool.uv.sources]
miraichan = { workspace = true }
# protocol adapters
melobot_telegram_protocol = { workspace = true }
# shared libs
lemony_utils = { workspace = true }
lemony_settings = { workspace = true }
lemony_checkers = { workspace = true }
lemony_llm_provider = { workspace = true }
lemony_storage_helper = { workspace = true }
lemony_images = { workspace = true }
lemony_network = { workspace = true }
lemony_media = { workspace = true }
lemony_onebot_utils = { workspace = true }
# plugins
mbplugin_checker_manager = { workspace = true }
mbplugin_deeeer = { workspace = true }
mbplugin_moelottery = { workspace = true }
mbplugin_recorder = { workspace = true }

[tool.pdm.scripts]
melobot = { cmd = ["python", "-m", "melobot"] }
deploy = { cmd = ["melobot", "run", "miracle_entrance.py"] }
dev = { cmd = ["miracle_entrance.py", "--debug"] }

[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "watchfiles>=0.24.0",
    "types-qrcode>=8.0.0.20241004",
    "types-lxml>=2024.11.8",
    "types-aiofiles>=24.1.0.20240626",
    "mypy>=1.19.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "pytest-sqlalchemy>=0.3.0",
    "pytest-sqlalchemy-mock>=0.1.7",
]

[tool.mypy]
follow_imports = "normal"
ignore_missing_imports = true
show_column_numbers = true
check_untyped_defs = true
disallow_untyped_defs = true
warn_return_any = true
warn_redundant_casts = true
disallow_untyped_calls = true
strict_equality = true
