# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x6a1bdd391
from pathlib import Path as _0x6a1bdd392
from typing import Any as _0x6a1bdd393

from melobot.plugin.base import PluginInfo as _0x6a1bdd398
from melobot.plugin.load import plugin_get_attr as _0x6a1bdd394

_0x6a1bdd395 = _0x6a1bdd392(__file__).parent
_0x6a1bdd396 = set(fname.split(".")[0] for fname in _0x6a1bdd391(_0x6a1bdd395))
_0x6a1bdd397 = _0x6a1bdd395.parts[-1]


def __getattr__(name: str) -> _0x6a1bdd393:
    return _0x6a1bdd394(_0x6a1bdd397, name, _0x6a1bdd396)


__plugin_info__: _0x6a1bdd398
__auto_gen_version__ = "2"
__version__ = "0.1.0a0"
