# This file is @generated by melobot cli.
# It is not intended for manual editing.
from .__plugin__ import recorder_models_share as _recorder_models
from .__plugin__ import recorder_service_share as _recorder_service
from .__plugin__ import recorder_db_share as _recorder_database

recorder_models = _recorder_models.get()
recorder_service = _recorder_service.get()
recorder_database = _recorder_database.get()

__all__ = ('recorder_models', 'recorder_service', 'recorder_database')
