# This file is @generated by melobot cli.
# It is not intended for manual editing.
from .__plugin__ import set_alias
from .__plugin__ import get_alias
from .__plugin__ import if_alias_exists



__all__ = ('set_alias', 'get_alias', 'if_alias_exists')
