# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x697e1c941
from pathlib import Path as _0x697e1c942
from typing import Any as _0x697e1c943

from melobot.plugin.base import PluginInfo as _0x697e1c948
from melobot.plugin.load import plugin_get_attr as _0x697e1c944

_0x697e1c945 = _0x697e1c942(__file__).parent
_0x697e1c946 = set(fname.split(".")[0] for fname in _0x697e1c941(_0x697e1c945))
_0x697e1c947 = _0x697e1c945.parts[-1]


def __getattr__(name: str) -> _0x697e1c943:
    return _0x697e1c944(_0x697e1c947, name, _0x697e1c946)


__plugin_info__: _0x697e1c948
__auto_gen_version__ = "2"
__version__ = "0.1.3"
