# This file is @generated by melobot cli.
# It is not intended for manual editing.
from .__plugin__ import get_session
from .__plugin__ import get_fileid
from .__plugin__ import get_filepath



__all__ = ('get_session', 'get_fileid', 'get_filepath')
