# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x67d1a71d1
from pathlib import Path as _0x67d1a71d2
from typing import Any as _0x67d1a71d3

from melobot.plugin.base import PluginInfo as _0x67d1a71d8
from melobot.plugin.load import plugin_get_attr as _0x67d1a71d4

_0x67d1a71d5 = _0x67d1a71d2(__file__).parent
_0x67d1a71d6 = set(fname.split(".")[0] for fname in _0x67d1a71d1(_0x67d1a71d5))
_0x67d1a71d7 = _0x67d1a71d5.parts[-1]


def __getattr__(name: str) -> _0x67d1a71d3:
    return _0x67d1a71d4(_0x67d1a71d7, name, _0x67d1a71d6)


__plugin_info__: _0x67d1a71d8
__auto_gen_version__ = "2"
__version__ = "0.1.0"
