# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x67af57211
from pathlib import Path as _0x67af57212
from typing import Any as _0x67af57213

from melobot import get_bot as _0x67af57214

_0x67af57215 = _0x67af57212(__file__).parent
_0x67af57216 = set(fname.split(".")[0] for fname in _0x67af57211(_0x67af57215))
_0x67af57217 = _0x67af57215.parts[-1]


def __getattr__(name: str) -> _0x67af57213:
    if name in _0x67af57216 or name.startswith("_"):
        raise AttributeError
    obj = _0x67af57214().get_share(_0x67af57217, name)
    if obj.static:
        return obj.get()
    return obj
