# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x67aacc901
from pathlib import Path as _0x67aacc902
from typing import Any as _0x67aacc903

from melobot import get_bot as _0x67aacc904

_0x67aacc905 = _0x67aacc902(__file__).parent
_0x67aacc906 = set(fname.split(".")[0] for fname in _0x67aacc901(_0x67aacc905))
_0x67aacc907 = _0x67aacc905.parts[-1]


def __getattr__(name: str) -> _0x67aacc903:
    if name in _0x67aacc906 or name.startswith("_"):
        raise AttributeError
    obj = _0x67aacc904().get_share(_0x67aacc907, name)
    if obj.static:
        return obj.get()
    return obj
