# This file is @generated by melobot cli.
# It is not intended for manual editing.
from .__plugin__ import dbcore_share as _database
from .__plugin__ import url_to_fileid
from .__plugin__ import get_filepath
from .utils import get_context_messages
from .utils import query_group_msg_count

database = _database.get()

__all__ = ('database', 'url_to_fileid', 'get_filepath', 'get_context_messages', 'query_group_msg_count')
